### ISSUE TITLE
API: User Authentication

### ISSUE THREAD

**Issue by AlissonRoss** [Sillor/timewise-server#3]

**Comment by Ric-KL** [comment]
API that manages JWT auth, password hashing and decrypting. Takes requests with email/password combos and gives responses with codes and a jwt key to be stored in a cookie or session storage.

**Comment by Ric-KL** [comment]
First implementation of user auth completed. API can now create and send jwt tokens and check hashed password against the user-provided ones. Moving on to add database functionality to upload user/pw combos to a database and compare from database, as well as basic data management as part of the Database Management task.
